routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@beranda')->name('beranda');
Route::get('caripeta/{id}', 'HomeController@caripeta');
Route::get('layer','HomeController@layerpeta');
Route::get('caritype','HomeController@caritype');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('ruanganajax', 'HomeController@ruangan')->name('ruangan.ajax');
Route::get('detail-peta', 'HomeController@detail')->name('detail');

Route::resource('gedungs', 'gedungController');
Route::get('gedunggeom/{id}', 'gedungController@getMapgedung')->name('gedunggeom');
Route::get('tengahgedunggeom/{id}', 'gedungController@getCentergedung')->name('tengahgedunggeom');

Route::resource('ruangans', 'ruanganController');
Route::get('ruangangeom/{id}', 'ruanganController@getMapruangan')->name('ruangangeom');
Route::get('tengahruangangeom/{id}', 'ruanganController@getCenterruangan')->name('tengahruangangeom');

Route::resource('fasilitas', 'fasilitasController');

Route::resource('ruanganFasilitas', 'ruanganFasilitasController');

app/Models/ruanganFasilitas.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class ruanganFasilitas
 * @package App\Models
 * @version October 25, 2018, 6:12 pm UTC
 *
 * @property \Illuminate\Database\Eloquent\Collection id
 * @property \App\Models\fasilitas fasilitas
 * @property integer id_ruangan
 * @property integer id_fasilitas
 * @property integer status
 * @property string foto
 */
class ruanganFasilitas extends Model
{
    public $table = 'ruangan_fasilitas';


    public $fillable = [
        'id_ruangan',
        'id_fasilitas',
        'status',
        'foto'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id_ruangan' => 'integer',
        'id_fasilitas' => 'integer',
        'status' => 'integer',
        'foto' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'id_ruangan' => 'required',
        'id_fasilitas' => 'required',
        'status' => 'required'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     **/
    public function ruangans()
    {
        return $this->belongsTo(\App\Models\ruangan::class, 'id_ruangan', 'id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function fasilitas()
    {
        return $this->belongsTo(\App\Models\fasilitas::class, 'id_fasilitas', 'id');
    }
}

app/Http/Controllers/ruanganFasilitasController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateruanganFasilitasRequest;
use App\Http\Requests\UpdateruanganFasilitasRequest;
use App\Repositories\ruanganFasilitasRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;
use App\Models\fasilitas;
use App\Models\ruangan;
use App\Models\ruanganFasilitas;
use Illuminate\Support\Facades\File;

class ruanganFasilitasController extends AppBaseController
{
    /** @var  ruanganFasilitasRepository */
    private $ruanganFasilitasRepository;

    public function __construct(ruanganFasilitasRepository $ruanganFasilitasRepo)
    {
        $this->ruanganFasilitasRepository = $ruanganFasilitasRepo;
    }

    /**
     * Display a listing of the ruanganFasilitas.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->ruanganFasilitasRepository->pushCriteria(new RequestCriteria($request));
        $ruanganFasilitas = $this->ruanganFasilitasRepository->all();
        $id = $request->id;
        if($id){
          $ruanganFasilitas = ruanganFasilitas::where('id_ruangan',$id)->get();
        }
        $ruangan = ruangan::find($id);
        return view('ruangan_fasilitas.index',compact('ruanganFasilitas','ruangan'));
    }

    /**
     * Show the form for creating a new ruanganFasilitas.
     *
     * @return Response
     */
    public function create(Request $request)
    {
      $id_ruangan = $request->id;
      //dd($id_ruangan);
      if(!$id_ruangan){
        return redirect()->back();
      }
        $fasilitas = fasilitas::pluck('nama','id');
        return view('ruangan_fasilitas.create',compact('fasilitas','id_ruangan'));
    }

    /**
     * Store a newly created ruanganFasilitas in storage.
     *
     * @param CreateruanganFasilitasRequest $request
     *
     * @return Response
     */
    public function store(CreateruanganFasilitasRequest $request)
    {
      $request->validate([
        'id_ruangan' => 'required',
        'id_fasilitas' => 'required',
        'foto' => 'image|mimes:jpg,png,jpeg,gif',
      ]);
        $input = $request->all();
        if ($request->hasFile('foto') && $request->foto->isValid()) {
            $path = 'img/foto';
            $oldfile = $input['foto'];

            $fileext = $request->foto->extension();
            $filename = uniqid("fotos-").'.'.$fileext;

            //Real File
            $filepath = $request->file('foto')->storeAs($path, $filename, 'local');
            //foto File
            $realpath = storage_path('app/'.$filepath);
            $input['foto'] = $filename;
            //hapus foto lama
            File::delete(storage_path('app'.'/'. $path . '/' . $oldfile));
            File::delete(public_path($path . '/' . $oldfile));
        }
        $ruanganFasilitas = $this->ruanganFasilitasRepository->create($input);

        Flash::success('Ruangan Fasilitas saved successfully.');

        return redirect(route('ruanganFasilitas.index','id='.$ruanganFasilitas->id_ruangan));
    }

    /**
     * Display the specified ruanganFasilitas.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $ruanganFasilitas = $this->ruanganFasilitasRepository->findWithoutFail($id);

        if (empty($ruanganFasilitas)) {
            Flash::error('Ruangan Fasilitas not found');

            return redirect(route('ruanganFasilitas.index','id='.$ruanganFasilitas->id_ruangan));
        }

        return view('ruangan_fasilitas.show')->with('ruanganFasilitas', $ruanganFasilitas);
    }

    /**
     * Show the form for editing the specified ruanganFasilitas.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id, Request $request)
    {
      $id_ruangan = $request->type;
      //dd($id_ruangan);
      if(!$id_ruangan){
        return redirect()->back();
      }
        $ruanganFasilitas = $this->ruanganFasilitasRepository->findWithoutFail($id);
        $fasilitas = fasilitas::pluck('nama','id');
        if (empty($ruanganFasilitas)) {
            Flash::error('Ruangan Fasilitas not found');

            return redirect(route('ruanganFasilitas.index','id='.$ruanganFasilitas->id_ruangan));
        }

        return view('ruangan_fasilitas.edit',compact('fasilitas','id_ruangan','ruanganFasilitas'));
    }

    /**
     * Update the specified ruanganFasilitas in storage.
     *
     * @param  int              $id
     * @param UpdateruanganFasilitasRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateruanganFasilitasRequest $request)
    {
        $ruanganFasilitas = $this->ruanganFasilitasRepository->findWithoutFail($id);

        if (empty($ruanganFasilitas)) {
            Flash::error('Ruangan Fasilitas not found');

            return redirect(route('ruanganFasilitas.index','id='.$ruanganFasilitas->id_ruangan));
        }

        $ruanganFasilitas = $this->ruanganFasilitasRepository->update($request->all(), $id);

        Flash::success('Ruangan Fasilitas updated successfully.');

        return redirect(route('ruanganFasilitas.index','id='.$ruanganFasilitas->id_ruangan));
    }

    /**
     * Remove the specified ruanganFasilitas from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $ruanganFasilitas = $this->ruanganFasilitasRepository->findWithoutFail($id);

        if (empty($ruanganFasilitas)) {
            Flash::error('Ruangan Fasilitas not found');

            return redirect(route('ruanganFasilitas.index','id='.$ruanganFasilitas->id_ruangan));
        }

        $this->ruanganFasilitasRepository->delete($id);

        Flash::success('Ruangan Fasilitas deleted successfully.');

        return redirect(route('ruanganFasilitas.index','id='.$ruanganFasilitas->id_ruangan));
    }
}

resources/views/ruangan_fasilitas/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Ruangan Fasilitas
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'ruanganFasilitas.store','files' => true,'data-parsley-validate']) !!}

                        @include('ruangan_fasilitas.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/ruangan_fasilitas/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Ruangan Fasilitas
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($ruanganFasilitas, ['route' => ['ruanganFasilitas.update', $ruanganFasilitas->id], 'method' => 'patch','files' => true,'data-parsley-validate','id'=>'demo-form2']) !!}

                        @include('ruangan_fasilitas.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/ruangan_fasilitas/fields.blade.php
    {!! Form::hidden('id_ruangan', $id_ruangan, null, ['class' => 'form-control']) !!}

<!-- Id Fasilitas Field -->
<div class="form-group col-sm-6">
    {!! Form::label('id_fasilitas', 'Id Fasilitas:') !!}
    {!! Form::select('id_fasilitas', $fasilitas, null, ['class' => 'form-control']) !!}
</div>

<!-- Status Field -->
<div class="form-group col-sm-6">
    {!! Form::label('status', 'Status:') !!}
    {!! Form::select('status', ['0' => 'Rusak', '1' => 'Baik'], null, ['class' => 'form-control']) !!}
</div>

<!-- Foto Field -->
<div class="form-group col-sm-6">
    {!! Form::label('foto', 'Foto:') !!}
    {!! Form::file('foto') !!}
</div>
<div class="clearfix"></div>


<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('ruanganFasilitas.index','id='.$id_ruangan) !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/ruangan_fasilitas/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Fasilitas Ruangan {{$ruangan->nama}}</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{{ route('ruanganFasilitas.create', 'id='.$ruangan->id) }}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('ruangan_fasilitas.table')
            </div>
        </div>
        <div class="text-center">
          <a onclick="javascript:history.back()" class="btn btn-primary">Back</a>
        </div>
    </div>
@endsection

resources/views/ruangan_fasilitas/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Ruangan Fasilitas
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('ruangan_fasilitas.show_fields')
                    <a href="{!! route('ruanganFasilitas.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/ruangan_fasilitas/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $ruanganFasilitas->id !!}</p>
</div>

<!-- Id Ruangan Field -->
<div class="form-group">
    {!! Form::label('id_ruangan', 'Id Ruangan:') !!}
    <p>{!! $ruanganFasilitas->id_ruangan !!}</p>
</div>

<!-- Id Fasilitas Field -->
<div class="form-group">
    {!! Form::label('id_fasilitas', 'Id Fasilitas:') !!}
    <p>{!! $ruanganFasilitas->id_fasilitas !!}</p>
</div>

<!-- Status Field -->
<div class="form-group">
    {!! Form::label('status', 'Status:') !!}
    <p>{!! $ruanganFasilitas->status !!}</p>
</div>

<!-- Foto Field -->
<div class="form-group">
    {!! Form::label('foto', 'Foto:') !!}
    <p>{!! $ruanganFasilitas->foto !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $ruanganFasilitas->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $ruanganFasilitas->updated_at !!}</p>
</div>

resources/views/ruangan_fasilitas/table.blade.php
<table class="table table-responsive" id="ruanganFasilitas-table">
    <thead>
        <tr>
            <th>Ruangan</th>
        <th>Fasilitas</th>
        <th>Status</th>
            <th colspan="2">Action</th>
        </tr>
    </thead>
    <tbody>
      @if($ruanganFasilitas)
        @foreach($ruanganFasilitas as $ruanganFasilitas)
            <tr>
                <td>{!! $ruanganFasilitas->ruangans->nama !!}</td>
                <td>{!! $ruanganFasilitas->fasilitas->nama !!}</td>
                <td>
                  @if($ruanganFasilitas->status==1)
                    Baik
                  @elseif($ruanganFasilitas->status==0)
                    Rusak
                  @else
                    Tidak Diketahui
                  @endif
                </td>
                <td>
                    {!! Form::open(['route' => ['ruanganFasilitas.destroy', $ruanganFasilitas->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{!! route('ruanganFasilitas.show', [$ruanganFasilitas->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                        <a href="{!! route('ruanganFasilitas.edit', [$ruanganFasilitas->id,'type=1']) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
      @endif
    </tbody>
</table>