routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@beranda')->name('beranda');
Route::get('caripeta/{id}', 'HomeController@caripeta');
Route::get('layer','HomeController@layerpeta');
Route::get('caritype','HomeController@caritype');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('ruanganajax', 'HomeController@ruangan')->name('ruangan.ajax');
Route::get('detail-peta', 'HomeController@detail')->name('detail');

Route::resource('gedungs', 'gedungController');
Route::get('gedunggeom/{id}', 'gedungController@getMapgedung')->name('gedunggeom');
Route::get('tengahgedunggeom/{id}', 'gedungController@getCentergedung')->name('tengahgedunggeom');

Route::resource('ruangans', 'ruanganController');
Route::get('ruangangeom/{id}', 'ruanganController@getMapruangan')->name('ruangangeom');
Route::get('tengahruangangeom/{id}', 'ruanganController@getCenterruangan')->name('tengahruangangeom');

Route::resource('fasilitas', 'fasilitasController');

Route::resource('ruanganFasilitas', 'ruanganFasilitasController');

app/Models/ruangan.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Phaza\LaravelPostgis\Eloquent\PostgisTrait;

/**
 * Class ruangan
 * @package App\Models
 * @version October 25, 2018, 5:57 pm UTC
 *
 * @property string nama
 */
class ruangan extends Model
{
    use PostgisTrait;

    public $table = 'ruangans';


    public $fillable = [
        'nama', 'geom'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'nama' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'nama' => 'required'
    ];

    protected $postgisFields = [
        'geom'
    ];

    protected $postgisTypes = [
        'geom' => [
            'geomtype' => 'geometry',
            'srid' => 0
        ]
    ];


}

app/Http/Controllers/ruanganController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateruanganRequest;
use App\Http\Requests\UpdateruanganRequest;
use App\Repositories\ruanganRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;
use App\Models\ruangan;

class ruanganController extends AppBaseController
{
    /** @var  ruanganRepository */
    private $ruanganRepository;

    public function __construct(ruanganRepository $ruanganRepo)
    {
        $this->ruanganRepository = $ruanganRepo;
    }

    /**
     * Display a listing of the ruangan.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->ruanganRepository->pushCriteria(new RequestCriteria($request));
        $ruangans = $this->ruanganRepository->all();

        return view('ruangans.index')
            ->with('ruangans', $ruangans);
    }

    /**
     * Show the form for creating a new ruangan.
     *
     * @return Response
     */
    public function create()
    {
        return view('ruangans.create');
    }

    /**
     * Store a newly created ruangan in storage.
     *
     * @param CreateruanganRequest $request
     *
     * @return Response
     */
    public function store(CreateruanganRequest $request)
    {
        $input = $request->all();
        $input['geom'] = "MULTIPOLYGON(".$input['geom'].")";
        $ruangan = $this->ruanganRepository->create($input);

        Flash::success('Ruangan saved successfully.');

        return redirect(route('ruangans.index'));
    }

    /**
     * Display the specified ruangan.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $ruangan = $this->ruanganRepository->findWithoutFail($id);

        if (empty($ruangan)) {
            Flash::error('Ruangan not found');

            return redirect(route('ruangans.index'));
        }

        return view('ruangans.show')->with('ruangan', $ruangan);
    }

    /**
     * Show the form for editing the specified ruangan.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $ruangan = $this->ruanganRepository->findWithoutFail($id);

        if (empty($ruangan)) {
            Flash::error('Ruangan not found');

            return redirect(route('ruangans.index'));
        }

        return view('ruangans.edit')->with('ruangan', $ruangan);
    }

    /**
     * Update the specified ruangan in storage.
     *
     * @param  int              $id
     * @param UpdateruanganRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateruanganRequest $request)
    {
        $ruangan = $this->ruanganRepository->findWithoutFail($id);
        $input = $request->all();
        $input['geom'] = "MULTIPOLYGON(".$input['geom'].")";
        if (empty($ruangan)) {
            Flash::error('Ruangan not found');

            return redirect(route('ruangans.index'));
        }

        $ruangan = $this->ruanganRepository->update($input, $id);

        Flash::success('Ruangan updated successfully.');

        return redirect(route('ruangans.index'));
    }

    /**
     * Remove the specified ruangan from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $ruangan = $this->ruanganRepository->findWithoutFail($id);

        if (empty($ruangan)) {
            Flash::error('Ruangan not found');

            return redirect(route('ruangans.index'));
        }

        $this->ruanganRepository->delete($id);

        Flash::success('Ruangan deleted successfully.');

        return redirect(route('ruangans.index'));
    }

    public function getMapruangan($id){
        if ($id != 'all'){
            $store = ruangan::where('id',$id)->get();
        }else{
            $store = ruangan::all();
        }
        $ret = config('value.t1');
        $i = 0;
        foreach ($store as $l){
            $ret['features'][$i] = config('value.t2');
            $ret['features'][$i]['geometry'] = $l->geom;
            $i++;
        }
        return response()->json($ret);
    }

    public function getCentergedung($id){
        $store = ruangan::select(DB::raw("ST_X(ST_Centroid(geom)) AS lon, ST_Y(ST_CENTROID(geom)) As lat"))
            ->where('id',$id)->first();
        return response()->json($store);
    }
}

resources/views/ruangans/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Ruangan
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'ruangans.store']) !!}

                        @include('ruangans.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/ruangans/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Ruangan
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($ruangan, ['route' => ['ruangans.update', $ruangan->id], 'method' => 'patch']) !!}

                        @include('ruangans.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/ruangans/fields.blade.php
<!-- Nama Field -->
<div class="form-group col-sm-6">
    {!! Form::label('nama', 'Nama:') !!}
    {!! Form::text('nama', null, ['class' => 'form-control']) !!}
</div>

<!-- Geom Field -->
<div class="form-group col-sm-12">
    <div id="map-content" style="width:100%;height:420px; z-index:50"></div>
    <a class="btn btn-primary btn-sm" id="delete-button">Delete</a>
    <label class="col-sm-12">Geom</label>
    <div class="col-sm-12">
        {!! Form::text('geom', null, ['class' => 'form-control','id'=>'geom']) !!}
    </div>
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('ruangans.index') !!}" class="btn btn-default">Cancel</a>
</div>

@section('scripts')
    <script>
        var drawingManager;
        var selectedShape;
        var map;

        function initMap() {
            map = new google.maps.Map(document.getElementById('map-content'),{
                center: new google.maps.LatLng(-0.94924, 100.35427),
                zoom: 18,
                mapTypeId: google.maps.MapTypeId.ROADMAP,
                disableDefaultUI: true,
                zoomControl: true,
                mapTypeControl: true
            });

            infoWindow = new google.maps.InfoWindow;

            if (navigator.geolocation)
            {
              navigator.geolocation.getCurrentPosition(function(position)
              {
                var pos =
                {
                  lat: position.coords.latitude,
                  lng: position.coords.longitude
                };

                infoWindow.setPosition(pos);
                infoWindow.setContent('Lokasi Saya.');
                infoWindow.open(map);
                map.setCenter(pos);
              },
              function()
              {
                handleLocationError(true, infoWindow, map.getCenter());
              });
            } else {
              // Browser doesn't support Geolocation
              handleLocationError(false, infoWindow, map.getCenter());
            }

            var polyOptions = {
                fillColor: 'blue',
                strokeColor: 'blue',
                draggable: true
            };

            drawingManager = new google.maps.drawing.DrawingManager({
                drawingMode: google.maps.drawing.OverlayType.POLYGON,
                drawingControlOptions: {
                    position: google.maps.ControlPosition.TOP_LEFT,
                    drawingModes: [
                        google.maps.drawing.OverlayType.POLYGON
                    ]
                },
                polygonOptions: polyOptions,
                map: map
            });

            //event digitasi di google map
            google.maps.event.addListener(drawingManager, 'overlaycomplete', function(event){
                if (event.type == google.maps.drawing.OverlayType.POLYGON){
                    //console.log('polygon path array', event.overlay.getPath().getArray());
                    var str_input ='((';
                    var i=0;
                    var coor = [];
                    $.each(event.overlay.getPath().getArray(), function(key, latlng){
                        var lat = latlng.lat();
                        var lon = latlng.lng();
                        coor[i] = lon +' '+ lat;
                        str_input += lon +' '+ lat +',';
                        i++;
                    });
                    str_input = str_input+''+coor[0]+'))';
                    $("#geom").val(str_input);
                    drawingManager.setDrawingMode(null);
                    drawingManager.setOptions({
                        drawingControl: false
                    });
                    // Add an event listener that selects the newly-drawn shape when the user mouses down on it.
                    var newShape = event.overlay;
                    newShape.type = event.type;
                    setSelection(newShape);
                    google.maps.event.addListener(newShape, 'click', function(){
                        setSelection(newShape);
                    });
                }
                function getCoordinate(){
                    var polygonBounds = newShape.getPath();
                    str_input ='((';
                    for(var i = 0 ; i < polygonBounds.length ; i++){
                        coor[i] = polygonBounds.getAt(i).lng() +' '+ polygonBounds.getAt(i).lat();
                        str_input += polygonBounds.getAt(i).lng() +' '+ polygonBounds.getAt(i).lat() +',';
                    }
                    str_input = str_input+''+coor[0]+'))';
                    $("#geom").val(str_input);
                }
                google.maps.event.addListener(newShape.getPath(), 'set_at', getCoordinate);
                google.maps.event.addListener(newShape.getPath(), 'insert_at', getCoordinate);
                google.maps.event.addListener(newShape.getPath(), 'remove_at', getCoordinate);
            });
            google.maps.event.addListener(drawingManager, 'drawingmode_changed', clearSelection);
            google.maps.event.addListener(map, 'click', clearSelection);
            google.maps.event.addDomListener(document.getElementById('delete-button'), 'click', deleteSelectedShape);

            drawingManager.setMap(map);
        }

        function clearSelection() {
            if (selectedShape) {
                selectedShape.setEditable(false);
                selectedShape = null;
            }
        }

        function setSelection(shape) {
            clearSelection();
            selectedShape = shape;
            shape.setEditable(true);
        }

        function deleteSelectedShape() {
            if (selectedShape) {
                $("#geom").val('');
                selectedShape.setMap(null);
                drawingManager.setOptions({
                    drawingControl: true
                });
            }
        }

    </script>

    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDIhFclffR-6pgFqaUP_d7ZU8fEUhCflZ0&libraries=drawing&callback=initMap"></script>
@endsection

resources/views/ruangans/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Ruangans</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('ruangans.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('ruangans.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/ruangans/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Ruangan
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('ruangans.show_fields')
                    <a href="{!! route('ruangans.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/ruangans/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $ruangan->id !!}</p>
</div>

<!-- Nama Field -->
<div class="form-group">
    {!! Form::label('nama', 'Nama:') !!}
    <p>{!! $ruangan->nama !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $ruangan->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $ruangan->updated_at !!}</p>
</div>


<!-- Geom Field -->
<div class="form-group">
    {!! Form::label('geom', 'Map:') !!}
    <div id="map-content" style="width:100%;height:420px; z-index:50"></div>
</div>

@section('scripts')
    <script>
        var map;

        function initMap() {
            map = new google.maps.Map(document.getElementById('map-content'),{
                center: new google.maps.LatLng(-0.915282, 100.460717),
                zoom: 16,
                mapTypeId: google.maps.MapTypeId.ROADMAP,
                disableDefaultUI: true,
                zoomControl: true,
                mapTypeControl: true
            });

            var polyOptions = {
                fillColor: 'blue',
                strokeColor: 'blue',
                draggable: true
            };
            infoWindow = new google.maps.InfoWindow;

            if (navigator.geolocation)
            {
              navigator.geolocation.getCurrentPosition(function(position)
              {
                var pos =
                {
                  lat: position.coords.latitude,
                  lng: position.coords.longitude
                };

                infoWindow.setPosition(pos);
                infoWindow.setContent('Lokasi Saya.');
                infoWindow.open(map);
                map.setCenter(pos);
              },
              function()
              {
                handleLocationError(true, infoWindow, map.getCenter());
              });
            } else {
              // Browser doesn't support Geolocation
              handleLocationError(false, infoWindow, map.getCenter());
            }
            getMap();
        }

        function getMap() {
            var curMap = new google.maps.Data();
            curMap.loadGeoJson('{!! route('ruangangeom',['id'=>$ruangan->id]) !!}');
            curMap.setStyle(function(feature){
                return({
                    fillColor: '#bd0d2b',
                    strokeColor: '#000000',
                    strokeWeight: 1,
                    fillOpacity: 0.3
                });
            });
            curMap.setMap(map);
            $.get('{!! route('tengahruangangeom',['id'=>$ruangan->id]) !!}',function(result){
                map.setCenter(new google.maps.LatLng(result.lat,result.lon));
                map.setZoom(16);
            });
        }
    </script>

    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC3UDFwI28UYpMQQqpV7YxlSBShk-7fGCc&callback=initMap"></script>

@endsection

resources/views/ruangans/table.blade.php
<table class="table table-responsive" id="ruangans-table">
    <thead>
        <tr>
            <th  style="width:70%">Nama</th>
            <th class="text-center">Action</th>
        </tr>
    </thead>
    <tbody>
    @foreach($ruangans as $ruangan)
        <tr>
            <td>{!! $ruangan->nama !!}</td>
            <td class="text-center">
                {!! Form::open(['route' => ['ruangans.destroy', $ruangan->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('ruangans.show', [$ruangan->id]) !!}" class='btn btn-success btn-xs'>detail</a>
                    <a href="{!! route('ruangans.edit', [$ruangan->id]) !!}" class='btn btn-info btn-xs'>Edit</a>
                    <a href="{!! route('ruanganFasilitas.index', 'id='.$ruangan->id) !!}" class='btn btn-warning btn-xs'>Fasilitas Ruangan</a>
                    {!! Form::button('Hapus', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>